name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: nyakaz73/heroku-django-deploy@v0.68
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email_address: ${{ secrets.HEROKU_EMAIL_ADDRESS }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          use_docker: true
